#
# configure install environment
#

- hosts: head
  become: yes
  become_user: root

  tasks:
  - name: ensure no default efi pxe configure exists
    file:
        path: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/net/grub.cfg"
        state: absent

  - name: load per node efi pxe configure
    template:
        src: templates/grub-net.cfg.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/net/grub.cfg-01-{{ node.eth|replace(':', '-') }}"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.pxeimg == "efi"

  - name: ensure no default bios pxe configure exists
    file:
        path: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/net/pxelinux.cfg/default"
        state: absent

  - name: load per node bios pxe configure
    template:
        src: templates/pxelinux.cfg.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/net/pxelinux.cfg/01-{{ node.eth|replace(':', '-') }}"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.pxeimg == "bios"

  - name: load per node autoyast install configuration
    template:
        src: templates/{{ node.hwtype }}-autoinst.xml.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/autoyast/{{ node.name }}-autoinst.xml"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.hwtype == "dss7500"

  - template:
        src: templates/{{ node.hwtype }}-autoinst.xml.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/autoyast/{{ node.name }}-autoinst.xml"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.hwtype == "r640"

  - template:
        src: templates/{{ node.hwtype }}-autoinst.xml.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/autoyast/{{ node.name }}-autoinst.xml"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.hwtype == "740xd"

  - template:
        src: templates/{{ node.hwtype }}-autoinst.xml.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/autoyast/{{ node.name }}-autoinst.xml"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.hwtype == "740xd2"

  - template:
        src: templates/{{ node.hwtype }}-autoinst.xml.j2
        dest: "{{ TFTP_BOOT_DIR }}/{{ OS_TFTP_TAG }}/autoyast/{{ node.name }}-autoinst.xml"
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ cluster[clustername] | dict2items }}"
    when: node.hwtype == "vm"
